TABLES = {}

TABLES['proxies'] = '''
CREATE TABLE `proxies` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `proxy` VARCHAR(250) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_good` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
    `latency` INT(10) NULL DEFAULT NULL,
    `speed` INT(10) NULL DEFAULT NULL,
    `send_to_mq` TIMESTAMP NULL DEFAULT NULL,
    `check_at` TIMESTAMP NULL DEFAULT NULL,
    `import_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `proxy` (`proxy`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
'''

__all__ = ['TABLES']
